services:
  pg:
    container_name: luiggi-pg
    image: postgres:18.1
    ports: ["6432:5432"]
    environment:
      POSTGRES_DB: luiggi
      POSTGRES_USER: luiggi
      POSTGRES_PASSWORD: 123456
      PGDATA: /mnt/postgresql/data/pgdata
    volumes:
      - ./docker/pgdata/data:/mnt/postgresql/data
    restart: always
    networks: ["luiggi-network"]

networks:
  luiggi-network:
    name: luiggi-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.210.0.0/16
