services:
  pg:
    container_name: luiggi-pg
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["6432:5432"]
    environment:
      POSTGRES_DB: luiggi
      POSTGRES_USER: luiggi
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./docker/pgdata/data:/var/lib/postgresql/18/docker
    restart: always
    networks: ["luiggi-network"]

networks:
  luiggi-network:
    name: luiggi-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.210.0.0/16
